# Generated by Django 5.2.6 on 2025-10-29 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_hab', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('camas_matrimoniales', models.PositiveIntegerField(default=0)),
                ('camas_individuales', models.PositiveIntegerField(default=0)),
                ('especiales', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Registro_Huespedes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=100)),
                ('identificacion', models.IntegerField()),
                ('procedencia', models.CharField(max_length=200)),
                ('razon', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=100, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=20, null=True)),
                ('preferencias', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'registro_huespedes',
            },
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('identificacion', models.IntegerField(blank=True, default=0)),
                ('telefono_domicilio', models.CharField(blank=True, max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('domicilio', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=50)),
                ('telefono_oficina', models.CharField(max_length=50)),
                ('formadepago', models.CharField(max_length=50)),
                ('check_in', models.DateTimeField(max_length=50)),
                ('check_out', models.DateTimeField(max_length=50)),
                ('companion', models.IntegerField()),
                ('nombre_compania', models.CharField(max_length=50, null=True)),
                ('compania_domicilio', models.CharField(max_length=50, null=True)),
                ('compania_ciudad', models.CharField(max_length=50, null=True)),
                ('compania_email', models.CharField(max_length=50, null=True)),
                ('hospedaje_deseado', models.CharField(max_length=50, null=True)),
                ('cotizado', models.IntegerField(null=True)),
                ('solicitado', models.IntegerField(null=True)),
                ('num_hues', models.IntegerField(null=True)),
                ('num_habt', models.IntegerField(null=True)),
                ('empleados', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=10)),
                ('solicitud', models.CharField(max_length=50, null=True)),
                ('observaciones', models.CharField(max_length=50, null=True)),
                ('confirmado', models.CharField(default='Pendiente', max_length=50, null=True)),
                ('huesped_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_como_principal', to='hotel.registro_huespedes')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupada', 'Ocupada'), ('Limpieza', 'Limpieza'), ('Mantenimiento', 'Mantenimiento')], default='Disponible', max_length=20)),
                ('precio', models.IntegerField()),
                ('tipo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.categorias')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.reservas')),
            ],
            options={
                'db_table': 'habitaciones',
            },
        ),
    ]
