# Generated by Django 5.2.6 on 2025-10-24 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hab_Categorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('vistas', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'hab_categorias',
            },
        ),
        migrations.CreateModel(
            name='Registro_Huespedes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=100)),
                ('identificacion', models.IntegerField()),
                ('procedencia', models.CharField(max_length=200)),
                ('razon', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=255)),
                ('codigo_usuario', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'registro_huespedes',
            },
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('telefono_domicilio', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('domicilio', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=50)),
                ('telefono_oficina', models.CharField(max_length=50)),
                ('formadepago', models.CharField(max_length=50)),
                ('check_in', models.DateTimeField(max_length=50)),
                ('check_out', models.DateTimeField(max_length=50)),
                ('companion', models.IntegerField()),
                ('nombre_compania', models.CharField(max_length=50, null=True)),
                ('compania_domicilio', models.CharField(max_length=50, null=True)),
                ('compania_ciudad', models.CharField(max_length=50, null=True)),
                ('compania_email', models.CharField(max_length=50, null=True)),
                ('hospedaje_deseado', models.CharField(max_length=50, null=True)),
                ('cotizado', models.IntegerField(null=True)),
                ('solicitado', models.IntegerField(null=True)),
                ('num_hues', models.IntegerField(null=True)),
                ('num_habt', models.IntegerField(null=True)),
                ('empleados', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('solicitud', models.CharField(max_length=50)),
                ('observaciones', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('precio', models.IntegerField()),
                ('piso', models.IntegerField(default=1)),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hab_categorias')),
            ],
            options={
                'db_table': 'habitaciones',
            },
        ),
    ]
