# Generated by Django 5.2.6 on 2025-10-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitaciones',
            name='piso',
            field=models.IntegerField(default=1),
        ),
    ]
