# Generated by Django 5.2.6 on 2025-10-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_huespedes',
            name='contacto',
        ),
        migrations.AddField(
            model_name='registro_huespedes',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='registro_huespedes',
            name='telefono',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registro_huespedes',
            name='identificacion',
            field=models.CharField(max_length=10),
        ),
    ]
