# Generated by Django 5.2.6 on 2025-10-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_registro_huespedes_contacto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitaciones',
            name='reserva',
        ),
        migrations.AddField(
            model_name='reservas',
            name='habitaciones_asignadas',
            field=models.ManyToManyField(blank=True, related_name='reservas_asignadas', to='hotel.habitaciones'),
        ),
    ]
