# Generated by Django 5.2.6 on 2025-10-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_reservas_identificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitaciones',
            name='categoria_id',
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='tipo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habitaciones',
            name='estado',
            field=models.CharField(max_length=1),
        ),
        migrations.DeleteModel(
            name='Hab_Categorias',
        ),
    ]
