# Generated by Django 5.2.6 on 2025-10-27 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_habitaciones_categoria_id_habitaciones_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_hab', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.AlterField(
            model_name='habitaciones',
            name='estado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='observaciones',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='solicitud',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='habitaciones',
            name='tipo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.categorias'),
        ),
    ]
