# Generated by Django 5.2.6 on 2025-10-29 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_habitaciones_reserva_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('total_noches', models.IntegerField()),
                ('subtotal_alojamiento', models.IntegerField()),
                ('impuestos', models.IntegerField(default=0)),
                ('total_facturado', models.IntegerField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de Pago'), ('Pagada', 'Pagada'), ('Anulada', 'Anulada')], default='Pendiente', max_length=20)),
                ('huesped', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='hotel.registro_huespedes')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='hotel.reservas')),
            ],
            options={
                'db_table': 'facturas',
            },
        ),
    ]
