# Generated by Django 5.2.6 on 2025-10-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitaciones',
            name='precio',
        ),
        migrations.AddField(
            model_name='categorias',
            name='precio_base',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='adicional_precio',
            field=models.IntegerField(default=0, help_text='Valor extra por vistas, balcón, etc. (se suma al precio base de la categoría)'),
        ),
    ]
