# Generated by Django 5.2.6 on 2025-10-27 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_categorias_alter_habitaciones_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitaciones',
            name='reserva',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel.reservas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservas',
            name='telefono',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='telefono_domicilio',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
