# Generated by Django 5.2.6 on 2025-10-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_habitaciones_reserva_alter_reservas_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='confirmado',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
