# Generated by Django 5.2.6 on 2025-10-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_habitaciones_precio_categorias_precio_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='compania_ciudad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='compania_domicilio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='compania_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='confirmado',
            field=models.CharField(blank=True, default='Pendiente', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='cotizado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='formadepago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta de Credito', 'Tarjeta de Crédito'), ('Transferencia', 'Transferencia Bancaria'), ('cobrar_compania', 'Cobrar a Compañía'), ('Otro', 'Otro')], default='Efectivo', max_length=50),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='hospedaje_deseado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='nombre_compania',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='num_habt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='num_hues',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='observaciones',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='solicitado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='solicitud',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
