# Generated by Django 5.2.6 on 2025-10-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_reservas_compania_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='companion',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
