# Generated by Django 5.2.6 on 2025-10-28 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_reservas_confirmado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitaciones',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.reservas'),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='confirmado',
            field=models.CharField(default='Pendiente', max_length=50, null=True),
        ),
    ]
