# Generated by Django 5.2.6 on 2025-10-30 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_reservas_companion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio', models.IntegerField()),
                ('stock_disponible', models.PositiveIntegerField(default=0)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_en_el_momento', models.IntegerField()),
                ('fecha_consumo', models.DateTimeField(auto_now_add=True)),
                ('pagado_inmediatamente', models.BooleanField(default=False)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='hotel.reservas')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel.producto')),
            ],
            options={
                'verbose_name_plural': 'Consumos',
                'db_table': 'consumos',
            },
        ),
    ]
