# Generated by Django 5.2.6 on 2025-10-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_habitaciones_reserva_alter_reservas_confirmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='camas_individuales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categorias',
            name='camas_matrimoniales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categorias',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorias',
            name='especiales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='tipo_hab',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
