# Generated by Django 5.2.6 on 2025-10-30 18:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_producto_consumo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name_plural': 'Facturas'},
        ),
        migrations.AddField(
            model_name='factura',
            name='subtotal_consumos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total_noches',
            field=models.IntegerField(default=0),
        ),
    ]
