# Generated by Django 5.2.6 on 2025-10-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_categorias_camas_individuales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitaciones',
            name='piso',
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='numero',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
