# Generated by Django 5.2.6 on 2025-10-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_alter_factura_options_factura_subtotal_consumos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='esta_activo',
            field=models.BooleanField(default=True),
        ),
    ]
