# Generated by Django 5.2.6 on 2025-10-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_producto_esta_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='estado_estancia',
            field=models.CharField(choices=[('Pendiente', 'Pendiente (No ha llegado)'), ('Activa', 'Activa (Checked-in)'), ('Completada', 'Completada (Checked-out)')], default='Pendiente', max_length=20),
        ),
    ]
