# Generated by Django 5.2.6 on 2025-10-30 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_reservas_estado_estancia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas',
            name='cotizado',
        ),
    ]
