# Generated by Django 5.2.6 on 2025-10-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_remove_reservas_cotizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas',
            name='companion',
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='num_hues',
        ),
        migrations.AddField(
            model_name='reservas',
            name='acompanantes',
            field=models.ManyToManyField(blank=True, related_name='reservas_como_acompanante', to='hotel.registro_huespedes'),
        ),
    ]
